### ISSUE TITLE
Switch to Python 3

### ISSUE THREAD

**Issue by sebastic** [Nextpertise/autorsyncbackup#47]
Python 2 will reach EOL next month.

Distributions are in the process to remove Python 2 because of that.

The next Debian stable release (bullseye) will most likely not include the Python 2 modules required for autorsyncbackup and hence will need to use their python3 variants then.

**Comment by teunis90** [comment]
I'm ok with moving completely to Python3 and drop Python2 support.
I've seen your Python3 compatibility PR #38. I prefer to move completely to Python3 instead of hotfixing by future imports. 

Unfortunately, I don't have the time right now to do this change myself.

**Comment by sebastic** [comment]
I'll prepare a python3 PR to replay my prior one.

**Comment by teunis90** [comment]
@sebastic I know a few instances still run on machines with Python3.5 available. Please avoid new features like `f''` formatting, etc.

Let's aim for broad Python3 support.

**Comment by sebastic** [comment]
Branch is available in my fork:

 https://github.com/sebastic/autorsyncbackup/commits/python3

Waiting for #46 to be merged so the branch can be rebased on top of that.

We've been running that branch in production since yesterday, three runs have completed successfully with it.

Our backup server and my development machine run Debian buster with Python 3.7, I'll also test it in a stretch VM with Python 3.5 and possibly jessie with Python 3.4.

I may also add a testsuite if that can be reasonably mocked, alternatively it may be possible to configure Travis to setup an environment in which a real backup job can be executed.

**Comment by sebastic** [comment]
jessie users will need to stick to a previous release, `python3-mailer` is not available there.

**Comment by teunis90** [comment]
Pulled #46

**Comment by sebastic** [comment]
The porting to Python 3 is complete for a little while now, I'm still in the process of adding tests to get 100% coverage.

The current setup requires python3-pytest-cov on buster for its `--cov-branch` support, if you'd like to run the tests on stretch or jessie as well I'll look into making that work too.

Our (internal) Jenkins has a job to run the tests for the python3 branch in my fork. Do you have any CI that can be used for this repo?

**Comment by teunis90** [comment]
We use Travis-CI for public projects. Do you have experience with that?

**Comment by sebastic** [comment]
No, I haven't used Travis myself.

The `--cov-branch` option was added in pytest-cov 2.5.0 which is [available in Ubuntu bionic](https://launchpad.net/ubuntu/+source/python-pytest-cov), so using `dist: bionic` for Travis should work.

**Comment by teunis90** [comment]
I think it's a good idea to set this up. I tried to give you access rights to our Travis-Account. I can't find a way to give non-GitHub organization members access.

Can this wait till first week of January? I'm about to start my holiday leave.

**Comment by sebastic** [comment]
This can certainly wait. My earlier message was mostly meant as a status update, and to get an idea about the CI options for this repo.

Once I have 100% test coverage or otherwise consider the changes done, I'll open a PR for the changes in the python3 branch. Adding a `.travis.yml` then should suffice to trigger Travis if it's already enabled for this repo.
