### ISSUE TITLE
Hookpoint's (Pre and Post backup scripts)

### ISSUE THREAD

**Issue by teunis90** [Nextpertise/autorsyncbackup#8]
Hook point's (Pre- and Post- backup scripts)

- Local and Remote via SSH
- Challenge to implement this with feature: #5 (Simultaneous jobs)

**Comment by lnoor** [comment]
implemented per 67871908b2ee7da49b5af0c0eff55c7e07ecc856,
doc left to do

**Comment by lnoor** [comment]
Documentation added per 1b540409c1a98047d74bec3eb37ccc0bf4faeaf2
